openapi: 3.0.0
info:
  title: Kids Faith Tracker API
  version: 1.0.0
paths:
  /api/groups/create:
    post:
      summary: Create a new group
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                members:
                  type: array
                  items:
                    type: string
              required:
                - name
      responses:
        '201':
          description: Group created
  /api/groups/add-member:
    post:
      summary: Add a child to a group
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupId:
                  type: string
                childId:
                  type: string
              required:
                - groupId
                - childId
      responses:
        '200':
          description: Child added
  /api/groups/{groupId}:
    get:
      summary: Get group info
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: groupId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Group object
  /api/groups:
    get:
      summary: List all groups
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of groups
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
